---
version: '3'

services:
  vizualizer:
    image: python:3.6
    command: python3 -m http.server
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    secrets:
      - source: my_secret_data
    environment:
      - MY_SECRET_DATA_FILE: /run/secrets/my_secret_data

secrets:
  my_secret_data:
    external: true
