version: "3"
services:
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - '5432:5432'
  kong:
    image: kong:0.10.2
    links:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_LOG_LEVEL=debug
    deploy:
      replicas: 3
