---
version: "3"
services:
  logdna:
    image: gliderlabs/logspout
    command: "syslog+tls://syslog-a.logdna.com:21418"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SYSLOG_STRUCTURED_DATA=logdna@48950
    deploy:
      mode: global
