version: "3"
services:
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - '5432:5432'
    networks:
      - internal
  kong:
    image: kong:0.10.2
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_LOG_LEVEL=debug
    deploy:
      replicas: 3
    networks:
      - internal
  proxy:
    image: nginx:stable
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - /compose/files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    configs:
      - source: nginx_vhost
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager

networks:
  internal:

configs:
  nginx_vhost:
    file: ./nginx_vhost.conf

