---
version: '3'

services:
  vizualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kong
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kong:
    external:
      name: infrastructure_internal