---
- hosts: server_swarm
  vars:
    version: latest
    expose_ports: []
    compose_path: '/code/swarm/'
    postgres_user:
    postgres_db:
  tasks:
    - name: Ensure location exists
      file:
        path: /composes/
        state: directory
      become: yes
    - name: Upload compose file
      template:
        src: "{{compose_path}}/docker-compose.{{service}}.{{version}}.yml"
        dest: "/composes/docker-compose.{{service}}.{{version}}.yml"
      become: yes
    - name: Deploy
      shell: "docker stack deploy -c /composes/docker-compose.{{service}}.{{version}}.yml {{service}} --with-registry-auth"
      become: yes
    - name: Expose ports if need be
      shell: "docker service update --publish-add {{item}} {{service}}_{{service}}"
      with_items: "{{expose_ports}}"
      become: yes
