---
- hosts: service_postgres_master
  vars:
    prefix: 'appointmentguru'
    service: 'medicalaid'
    postgres_db_name: "{{prefix}}_{{service}}"
    postgres_db_user: "{{prefix}}_{{service}}"
    postgres_db_password: 148C9C4E-DC43-462F-908D-DB89819DA22B
    postgres_db_host: 10.135.55.211
  roles:
    - { role: postgresdb, tags: ['postgres'] }

- hosts: server_swarm
  vars:
    slack_token: T4HRUBFLP/B61FK6CNL/kcOV37xTmAxYv1OfAWmkzE6L

    kong_admin_base_url: "http://46.101.101.99/manage"
    kong_base_url: "http://46.101.101.99"
    kong_admin_username: appointmentguru
    kong_admin_password: 4f6ae149-a6e1-45b7-8abc-dbf87f22e90b
    kong_proxy: true
    kong_plugins:
      - name: cors
        config: {}
      - name: rate-limiting
        config:
          config.second: 10
          config.hour: 10000

    docker_version: latest
    docker_org: appointmentguru
    docker_image: medicalaid
    docker_service: medicalaid
    docker_expose_ports: []

    prefix: 'appointmentguru'
    service: 'medicalaid'
    postgres_db_name: "{{prefix}}_{{service}}"
    postgres_db_user: "{{prefix}}_{{service}}"
    postgres_db_password: 148C9C4E-DC43-462F-908D-DB89819DA22B
    postgres_db_host: 10.135.55.211

    docker_environment:
      - key: DEBUG
        value: False
      - key: DATABASE_NAME
        value: "{{postgres_db_name}}"
      - key: DATABASE_USER
        value: "{{postgres_db_user}}"
      - key: DATABASE_PASSWORD
        value: "{{postgres_db_password}}"
      - key: DATABASE_HOST
        value: "{{postgres_db_host}}"
      - key: ALLOWED_HOSTS
        value: "{{docker_service}}"

  roles:
    - djangoapp
    - kongapi

  post_tasks:
    - name: Tell slack
      slack:
        token: '{{slack_token}}'
        msg: 'Deployed: {{docker_service}}:{{docker_version}} using image: {{docker_org}}/{{docker_image}}:{{docker_version}}'
      delegate_to: localhost
      when: slack_token is defined