---
- name: Create droplet
  hosts:
   - localhost
  vars:
      swarm_name: production
      swarm_nodes: 4
  roles:
    - role: swarmdroplet

- name: Harden Droplet
  gather_facts: False # the server may not be started yet
  hosts: harden
  roles:
    - role: securedroplet
      ansible_user: root
      users: "{{ ssh_users }}"
      server_type: "swarm"

- name: Refresh inventory
  hosts:
    - localhost
  tasks:
    - meta: refresh_inventory

- name: Install swarm
  become: yes
  become_method: sudo
  hosts:
  - server_swarm_production
  vars:
      swarm_name: production
      swarm_nodes: 4
  roles:
    - role: swarm
