---
- hosts: localhost
  tasks:
  - name: Create a new release
    github_release:
      user: "{{github_user}}"
      token: "{{github_password}}"
      repo: School
      action: create_release
      tag: patch
      target: baseline
      name: Baseline release
      body: Testing creating releases with magic