- hosts: localhost
  tasks:
    - name: install python name script
      pip:
        name: petname
        state: present
    - name: get a name
      command: petname --words 3
      register: petname
    - debug: var=petname.stdout

    # - command: "docker info --format '{%raw%}{{json .Swarm.ControlAvailable}}'{%endraw%}"
    #   register: result
    #   become: true
    # - debug: msg='Add tag manager'
    #   when: result.stdout == 'true'
    # - debug: msg='Remove tag manager'
    #   when: result.stdout != 'true'

