---
- name: Ensure location exists
  file:
    path: /composes/
    state: directory
  become: yes
- name: Upload compose file
  template:
    src: "docker-compose.yml"
    dest: "/composes/docker-compose.{{docker_service}}.{{docker_version}}.yml"
  become: yes
- name: login to dockerhub
  docker_login:
    username: toast38coza
    password: budry0kibri
    email: christo@appointmentguru.co
    state: present
  become: yes
- name: Pull latest image
  shell: "docker pull {{docker_org}}/{{docker_image}}:{{docker_version}}"
  become: yes
- name: Deploy
  shell: "docker stack deploy -c /composes/docker-compose.{{docker_service}}.{{docker_version}}.yml {{docker_service}} --with-registry-auth"
  become: yes
- name: Expose ports if need be
  shell: "docker service update --publish-add {{item}} {{docker_service}}_{{docker_service}}"
  with_items: "{{docker_expose_ports}}"
  become: yes
- name: log out dockerhub
  docker_login:
    username: toast38coza
    password: budry0kibri
    email: christo@appointmentguru.co
    state: absent
  become: yes
